services:
  teletrans:
    image: teletrans:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ../credentials.json:/usr/src/app/credentials.json
    logging:
      driver: none
